token: "ODQ0NDkyMDI4NDMxMTcxNTk0.YKTMfQ.B0ELBnQ0ugPw5jscu9arAY3d9_E"
ActivityType: "Listening"
statusText: "!help"
status: "online"
BotName: "TEST-BOT"
DevMode: false
DevUserID: "801084631159013378"
CommandPrefix: "!"
TerminalChannel: "821090120316878880"
TerminalChannelName: "Terminal"
DefaultRole: "821850631740063804"
UserJoinEventEnabled: true
UserLeaveEventEnabled: true
logging: true
